<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class StoreSPTIndukRequest extends FormRequest
{
    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'spt_id' => 'required|string|uuid|exists:spt,id',
            'dpp_a1' => 'required|numeric',
            'dpp_a2' => 'required|numeric',
            'dpp_a3' => 'required|numeric',
            'dpp_a4' => 'required|numeric',
            'dpp_a5' => 'required|numeric',
            'dpp_a6' => 'required|numeric',
            'dpp_a7' => 'required|numeric',
            'dpp_a8' => 'required|numeric',
            'dpp_a9' => 'required|numeric',
            'dpp_a10' => 'required|numeric',
            'dpp_ab' => 'required|numeric',
            'dpp_suma' => 'required|numeric',
            'dpp_lain_a1' => 'required|numeric',
            'dpp_lain_a2' => 'required|numeric',
            'dpp_lain_a3' => 'required|numeric',
            'dpp_lain_a4' => 'required|numeric',
            'dpp_lain_a5' => 'required|numeric',
            'dpp_lain_a6' => 'required|numeric',
            'dpp_lain_a7' => 'required|numeric',
            'dpp_lain_a8' => 'required|numeric',
            'dpp_lain_a9' => 'required|numeric',
            'dpp_lain_a10' => 'required|numeric',
            'dpp_lain_ab' => 'required|numeric',
            'dpp_lain_suma' => 'required|numeric',
            'ppn_a1' => 'required|numeric',
            'ppn_a2' => 'required|numeric',
            'ppn_a3' => 'required|numeric',
            'ppn_a4' => 'required|numeric',
            'ppn_a5' => 'required|numeric',
            'ppn_a6' => 'required|numeric',
            'ppn_a7' => 'required|numeric',
            'ppn_a8' => 'required|numeric',
            'ppn_a9' => 'required|numeric',
            'ppn_a10' => 'required|numeric',
            'ppn_ab' => 'required|numeric',
            'ppn_suma' => 'required|numeric',
            'ppnbm_a1' => 'required|numeric',
            'ppnbm_a2' => 'required|numeric',
            'ppnbm_a3' => 'required|numeric',
            'ppnbm_a4' => 'required|numeric',
            'ppnbm_a5' => 'required|numeric',
            'ppnbm_a6' => 'required|numeric',
            'ppnbm_a7' => 'required|numeric',
            'ppnbm_a8' => 'required|numeric',
            'ppnbm_a9' => 'required|numeric',
            'ppnbm_a10' => 'required|numeric',
            'ppnbm_ab' => 'required|numeric',
            'ppnbm_suma' => 'required|numeric',
            'dpp_ba' => 'required|numeric',
            'dpp_bb' => 'required|numeric',
            'dpp_bc' => 'required|numeric',
            'dpp_bd' => 'required|numeric',
            'dpp_be' => 'required|numeric',
            'dpp_bf' => 'required|numeric',
            'dpp_bg' => 'required|numeric',
            'dpp_bh' => 'required|numeric',
            'dpp_bi' => 'required|numeric',
            'dpp_bj' => 'required|numeric',
            'dpp_lain_ba' => 'required|numeric',
            'dpp_lain_bb' => 'required|numeric',
            'dpp_lain_bc' => 'required|numeric',
            'dpp_lain_bd' => 'required|numeric',
            'dpp_lain_be' => 'required|numeric',
            'dpp_lain_bf' => 'required|numeric',
            'dpp_lain_bg' => 'required|numeric',
            'dpp_lain_bh' => 'required|numeric',
            'dpp_lain_bi' => 'required|numeric',
            'dpp_lain_bj' => 'required|numeric',
            'ppn_ba' => 'required|numeric',
            'ppn_bb' => 'required|numeric',
            'ppn_bc' => 'required|numeric',
            'ppn_bd' => 'required|numeric',
            'ppn_be' => 'required|numeric',
            'ppn_bf' => 'required|numeric',
            'ppn_bg' => 'required|numeric',
            'ppn_bh' => 'required|numeric',
            'ppn_bi' => 'required|numeric',
            'ppn_bj' => 'required|numeric',
            'ppnbm_ba' => 'required|numeric',
            'ppnbm_bb' => 'required|numeric',
            'ppnbm_bc' => 'required|numeric',
            'ppnbm_bd' => 'required|numeric',
            'ppnbm_be' => 'required|numeric',
            'ppnbm_bf' => 'required|numeric',
            'ppnbm_bg' => 'required|numeric',
            'ppnbm_bh' => 'required|numeric',
            'ppnbm_bi' => 'required|numeric',
            'ppnbm_bj' => 'required|numeric',
            'ppn_ca' => 'required|numeric',
            'ppn_cb' => 'required|numeric',
            'ppn_cc' => 'required|numeric',
            'ppn_cd' => 'required|numeric',
            'ppn_ce' => 'required|numeric',
            'ppn_cf' => 'required|numeric',
            'ppn_cg' => 'required|numeric',
            'ppn_ch' => 'nullable|string',
            'dpp_kms' => 'required|numeric',
            'ppn_kms' => 'required|numeric',
            'ppn_pkpm' => 'required|numeric',
            'ppnbm_da' => 'required|numeric',
            'ppnbm_db' => 'required|numeric',
            'ppnbm_dc' => 'required|numeric',
            'ppnbm_dd' => 'required|numeric',
            'ppnbm_de' => 'required|numeric',
            'ppnbm_df' => 'required|boolean',
            'dpp_ea' => 'required|numeric',
            'dpp_eb' => 'required|numeric',
            'dpp_ec' => 'required|numeric',
            'dpp_lain_ea' => 'required|numeric',
            'dpp_lain_eb' => 'required|numeric',
            'dpp_lain_ec' => 'required|numeric',
            'ppn_ea' => 'required|numeric',
            'ppn_eb' => 'required|numeric',
            'ppn_ec' => 'required|numeric',
            'ppnbm_ea' => 'required|numeric',
            'ppnbm_eb' => 'required|numeric',
            'ppnbm_ec' => 'required|numeric',
            'dpp_fa' => 'required|numeric',
            'dpp_fb' => 'required|numeric',
            'dpp_fc' => 'required|numeric',
            'dpp_lain_fa' => 'required|numeric',
            'dpp_lain_fb' => 'required|numeric',
            'dpp_lain_fc' => 'required|numeric',
            'ppn_fa' => 'required|numeric',
            'ppn_fb' => 'required|numeric',
            'ppn_fc' => 'required|numeric',
            'ppnbm_fa' => 'required|numeric',
            'ppnbm_fb' => 'required|numeric',
            'ppnbm_fc' => 'required|numeric',
            'ppnbm_fd' => 'required|boolean',
            'spt_document' => 'required|string',
            'spt_result' => 'required|string',
            'ttd_name' => 'required|string',
            'ttd_position' => 'required|string',
            'ttd_date' => 'required|date',
        ];
    }
}